contact_links:
  - about: Ask a question or request support here
    name: Ask for Support
    url: >-
      https://github.com/Tranzact-Network/tranzact-blockchain/discussions/new?category=support
  - about: Request a new feature or idea here
    name: Make a Request
    url: >-
      https://github.com/Tranzact-Network/tranzact-blockchain/discussions/new?category=ideas
  - about: Get support on the Tranzact Discord chat channels.
    name: Join the Discord support chat
    url: 'https://discord.gg/r2HGpA73EU'
